version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
  spark-worker-3:

    image: spark-worker
    container_name: spark-worker-3
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8083:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  db:
    image: postgres
    container_name: docker-django-vue-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    restart: unless-stopped
    ports:
      - "5432:5432"
  django:
    build:
      context: .
      dockerfile: docker/Backend.Dockerfile
    container_name: docker-django-vue-backend
    command: ./docker/backend_setup.sh
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: db
    volumes:
      - shared-workspace:/opt/workspace
    ports:
      - "8002:8000"
    depends_on:
      - db
  vue:
    build:
      context: .
      dockerfile: docker/FrontendDockerfile
    container_name: docker-django-vue-frontend
    command: ./docker/frontend_setup.sh
    volumes:
      - .:/app
    ports:
      - "8084:8080"
    depends_on:
      - django

