# Generated by Django 3.2.5 on 2021-07-11 06:57

from django.db import migrations
import osm_jet.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=osm_jet.fields.DjangoManyToMany(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=osm_jet.fields.DjangoManyToMany(blank=True, help_text='Specific permissions for this user.', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
